### ISSUE TITLE
Concat method should have an option for new line breaks

### ISSUE THREAD

**Issue by Ardakilic** [eserozvataf/sey#25]
Currently, when you `concat()` files, they are merged without a new line for each one. This may produce errors on production:

Let's say you have 2 files to be merged, `a` and `b`:

if `a`'s last line starts with a line comment, and `b` starts with a block comment, it produces a syntax error:

E.g, from my minified vendor.js file:

```
//# sourceMappingURL=bootstrap-tagsinput.min.js.map/*!
 DataTables 1.10.11
 ©2008-2015 SpryMedia Ltd - datatables.net/license
*/
```

**Comment by eserozvataf** [comment]
Thank you for your feedback, it's a planned feature for forthcoming releases.

**Comment by eserozvataf** [comment]
check out new release. it seems it's working now.

**Comment by Ardakilic** [comment]
Thank you, I can confirm this is solved! :tada:
