### ISSUE TITLE
The fonts processed with sey are broken.

### ISSUE THREAD

**Issue by Ardakilic** [eserozvataf/sey#26]
When you process fonts in sey, they are broken.

Chrome developer tools gives me these errors:

```
Failed to decode downloaded font: sey-processed-font.ttf
website/:1 OTS parsing error: incorrect entrySelector for table directory
```

```
Failed to decode downloaded font: sey-processed-font2.ttf
website/:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
```

**Comment by eserozvataf** [comment]
reading files with utf-8 encoding causes this issue, they lose their binary integrity. I'll be looking for solutions for this. your suggestions are welcome.

**Comment by Ardakilic** [comment]
If this will be solved inside sey without a package, I'd suggest checking mime types of each file before handling, but I wonder how this'll affect the overall performance. Another option is to set a new parameter to `src()` method to tell sey them to treat them as binary in api method as you suggested.

In configuration method, this can be a multi-dimensional array:

Not true in real life, but you'll get my idea:

`src: ['./src/**/*.css', ['./src/**/*.ts' => false], ['./src/**/*.ttf' => true], ''],`

But I'm sure there are alternatives as packages.

**Comment by eserozvataf** [comment]
fixed.

with the aid of npm package `isbinaryfile`, sey distinguishes whether a file is binary or not.

thanks for feedback.
